### ISSUE TITLE
Metastudent can easily be installed using sudo

### ISSUE THREAD

**Issue by anshkapil** [Rostlab/MetaStudent#4] opened 2015-12-14 23:13 UTC
@jmcejuela 

We can very easily install the Metastudent tool and all its dependencies using sudo for a Debian based system.

But in the package installation, there is one file missing and a minor code bug too. But we are able to fix it and run the tool and get results too.

So should we update the readme accordingly? i.e. mentioning steps to copy file from git ? Or contacting Tobias for the error will be a better solution ?

Regards,
Ansh , Ana and Manuel

**Comment by juanmirocks** [comment] 2016-01-21 16:06
Thanks @anshkapil -- Sorry for coming late to this one.

If you know how to solve the error, go ahead and commit your changes. Note, however, that we require that the tool can be installed directly from source, not from the debian package. Great that you provide how to install it via apt-get, but we also need to know how to install it from this repo source or otherwise know how to generate the debian package.

**Comment by juanmirocks** [comment] 2016-01-21 16:06
See https://github.com/Rostlab/MetaStudent/issues/5

**Comment by juanmirocks** [comment] 2016-02-02 10:12
Duplicate of #5

**Closed as completed by juanmirocks** 2016-02-02 10:12 UTC
Labels: duplicate
